name: C:\Users\samle\AppData\Local\ESRI\conda\envs\arcgispro-pyre
channels:
- conda-forge
- esri
- defaults
dependencies:
- cloudpickle=0.6.1=py_0
- cytoolz=0.9.0.1=py36hfa6e2cd_1001
- dask-core=1.1.1=py_0
- imageio=2.4.1=py36_1000
- jpeg=9c=hfa6e2cd_1001
- libtiff=4.0.9=h36446d0_1002
- networkx=2.2=py_1
- olefile=0.46=py_0
- pandoc=2.6=0
- pillow=5.0.0=py36_0
- pyrsistent=0.14.9=py36hfa6e2cd_1000
- pywavelets=1.0.1=py36h452e1ab_1000
- scikit-image=0.14.2=py36h6538335_0
- toolz=0.9.0=py_1
- anaconda=custom=py36h363777c_0
- asn1crypto=0.24.0=py36_0
- atomicwrites=1.3.0=py_0
- attrs=18.2.0=py36h28b3542_0
- backcall=0.1.0=py36_0
- blas=1.0=mkl
- bleach=3.1.0=py36_0
- ca-certificates=2019.1.23=0
- certifi=2018.11.29=py36_0
- cffi=1.12.1=py36h7a1dbc1_0
- cftime=1.0.3.4=py36h8c2d366_0
- chardet=3.0.4=py36_1
- colorama=0.4.1=py36_0
- cycler=0.10.0=py36h009560c_0
- decorator=4.3.2=py36_0
- entrypoints=0.3=py36_0
- et_xmlfile=1.0.1=py36h3d2d736_0
- fastcache=1.0.2=py36hfa6e2cd_2
- graphviz=2.38=hfd603c8_2
- html5lib=1.0.1=py36_0
- icu=58.2=ha66f8fd_1
- idna=2.8=py36_0
- ipykernel=5.1.0=py36h39e3cac_0
- ipython=7.3.0=py36h39e3cac_0
- ipython_genutils=0.2.0=py36h3c5d0ee_0
- ipywidgets=7.4.2=py36_0
- jdcal=1.4=py36_0
- jinja2=2.10=py36_0
- jsonschema=2.6.0=py36h7636477_0
- jupyter=1.0.0=py36_7
- jupyter_client=5.2.4=py36_0
- jupyter_console=6.0.0=py36_0
- jupyter_core=4.4.0=py36_0
- jupyterlab=0.35.3=py36_0
- jupyterlab_launcher=0.13.1=py36_0
- jupyterlab_server=0.2.0=py36_0
- kiwisolver=1.0.1=py36h6538335_0
- libpng=1.6.36=h2a8f88b_0
- libsodium=1.0.16=h9d3ae62_0
- m2w64-gcc-libgfortran=5.3.0=6
- m2w64-gcc-libs=5.3.0=7
- m2w64-gcc-libs-core=5.3.0=7
- m2w64-gmp=6.1.0=2
- m2w64-libwinpthread-git=5.0.0.4634.697f757=2
- markupsafe=1.1.1=py36he774522_0
- mistune=0.8.4=py36he774522_0
- mkl_fft=1.0.6=py36hdbbee80_0
- mkl_random=1.0.1=py36h77b88f5_1
- more-itertools=5.0.0=py36_0
- mpmath=1.1.0=py36_0
- msys2-conda-epoch=20160418=1
- nbformat=4.4.0=py36h3a5bc1b_0
- nose=1.3.7=py36_2
- notebook=5.7.4=py36_0
- numexpr=2.6.8=py36h9ef55f4_0
- numpy=1.15.1=py36ha559c80_0
- numpy-base=1.15.1=py36h8128ebf_0
- openpyxl=2.6.0=py36_0
- openssl=1.0.2r=he774522_0
- pandas=0.24.1=py36ha925a31_0
- pandocfilters=1.4.2=py36_1
- parso=0.3.4=py36_0
- patsy=0.5.1=py36_0
- pickleshare=0.7.5=py36_0
- pip=19.0.3=py36_0
- pluggy=0.9.0=py36_0
- prompt_toolkit=2.0.9=py36_0
- py=1.8.0=py36_0
- pycparser=2.19=py36_0
- pygments=2.3.1=py36_0
- pyopenssl=19.0.0=py36_0
- pyparsing=2.3.1=py36_0
- pyqt=5.9.2=py36h6538335_2
- pyshp=2.0.1=py36_0
- pysocks=1.6.8=py36_0
- pytest=4.3.0=py36_0
- python=3.6.8=h9f7ef89_7
- python-dateutil=2.8.0=py36_0
- python-graphviz=0.8.4=py36_1
- pyzmq=18.0.0=py36ha925a31_0
- qt=5.9.6=vc14h1e9a669_2
- qtconsole=4.4.3=py36_0
- requests=2.21.0=py36_0
- scikit-learn=0.20.1=py36hb854c30_0
- scipy=1.1.0=py36h4f6bf74_1
- seaborn=0.9.0=py36_0
- send2trash=1.5.0=py36_0
- setuptools=40.8.0=py36_0
- simplegeneric=0.8.1=py36_2
- sip=4.19.8=py36h6538335_0
- six=1.12.0=py36_0
- sqlite=3.26.0=he774522_0
- statsmodels=0.9.0=py36h452e1ab_0
- terminado=0.8.1=py36_1
- testpath=0.4.2=py36_0
- tornado=5.1.1=py36hfa6e2cd_0
- traitlets=4.3.2=py36h096827d_0
- urllib3=1.24.1=py36_0
- vc=14.1=h0510ff6_4
- vs2015_runtime=14.15.26706=h3a45250_0
- wcwidth=0.1.7=py36h3d5aa90_0
- webencodings=0.5.1=py36_1
- wheel=0.33.1=py36_0
- widgetsnbextension=3.4.2=py36_0
- win_inet_pton=1.1.0=py36_0
- wincertstore=0.2=py36h7fe50ca_0
- winkerberos=0.7.0=py36_1
- winpty=0.4.3=4
- xlrd=1.2.0=py36_0
- xlwt=1.3.0=py36h1a4751e_0
- zeromq=4.3.1=h33f27b4_3
- zlib=1.2.11=h62dcd97_3
- arcgis=1.5.3=py36h66efe7d_1
- arcgispro=2.3=h35c310c_0
- cryptography=2.3.1=py36h9066843_0
- despatch=0.1.0=py36_0
- freetype=2.8=h51f8f2c_1
- future=0.16.0=py36_1
- gdal=2.1.1=arcgispro_1
- h5py=2.8.0=py36_arcgispro_4
- icc_rt=2018.0.2=arcgispro_0
- intel-openmp=2018.0.3=arcgispro_0
- jedi=0.12.1=py36_0
- keyring=13.2.1=py36_0
- matplotlib=2.2.3=py36_0e
- mkl=2018.0.3=arcgispro_0
- nbconvert=5.3.1=py36_1
- netcdf4=1.4.1=py36_arcgispro_3
- prometheus_client=0.3.1=py36_0
- pypdf2=1.26.0=py_2
- pytz=2018.5=py36_0
- pywin32-ctypes=0.2.0=py36he119be9_0
- pywinpty=0.5=py36_0
- sympy=1.2=py36_0
- x86cpu=0.4=py36_1
prefix: C:\Users\samle\AppData\Local\ESRI\conda\envs\arcgispro-pyre

